name: Build Paper
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_pr: ${{ steps.PR.outputs.pr_found }}
    steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.has_pr == 'false'
    steps:
      - name: Checkout action meta
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Initialize Workspace
        uses: ./.github/actions/init-workspace
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.sha }}
          event_file: ${{ github.event_path }}
          event_name: ${{ github.event_name }}
          files: "**/build/test-results/test/TEST-*.xml"
          comment_mode: off
