name: Build Paper Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  diffpublish:
    name: Generate Diff Patch
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'publish-diff') }}
    steps:
      - name: Checkout action meta
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Initialize Workspace
        uses: ./.github/actions/init-workspace
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      - name: Apply Patches for Base Repository
        working-directory: base
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace
      - name: Generate diff between files
        run: |
          diff \
            --unified=3 \
            --recursive \
            --exclude='.git' \
            --exclude='.mcassetsroot' \
            base/paper-server/src/minecraft/java \
            paper-server/src/minecraft/java \
            > raw.diff \
            || true
      - name: Apply diff onto base paper server
        run: |
          git apply \
            --directory=base/paper-server \
            raw.diff
      - name: Commit diff
        working-directory: 'base/paper-server/src/minecraft/java'
        run: |
          git add .
          git commit -m "Generated Patches Diff"
      - name: Generate commit patch
        working-directory: 'base/paper-server/src/minecraft/java'
        run: |
          git format-patch -1 HEAD \
            --stdout \
            --no-signature \
            -- . \
          > patch-${{ github.event.pull_request.number }}.patch
      - name: Upload patch to pastes.dev
        id: paste
        run: |
          raw_url=$(curl -s -T base/paper-server/src/minecraft/java/patch-${{ github.event.pull_request.number }}.patch \
            -H "Content-Type: text/x-diff" \
            https://api.pastes.dev/post)
          paste_url=$(echo "$raw_url" \
            | sed -e 's|^https://pastes.dev/|https://api.pastes.dev/|')  
          echo "paste_url=$paste_url" >> $GITHUB_OUTPUT
      - name: Find existing Diff Viewer comment
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- bot: paperclip-pr-build -->'
      - name: Create or update Diff Viewer comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <!-- bot: paperclip-pr-build -->
            ## 🖇️ Patch Diff Viewer
            Head over to [diffs.dev](https://diffs.dev), and paste in the URL below to view an enhanced view of the diff:
            ${{ steps.paste.outputs.paste_url }}

            *Last updated for: ${{ github.event.pull_request.head.sha }}*

  paperclip:
    name: Create & Publish Artifacts
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'publish-pr') }}
    permissions:
      packages: write # To upload the PR
      actions: write # To get information about the uploading workflow run and to delete the run artifacts
      contents: write # To download the `maven-publish` artifact, and to be able to create commit comments
      issues: write # To be able to create PR comments
      pull-requests: write # To be able to create PR comments
    steps:
      - name: Checkout action meta
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Initialize Workspace
        uses: ./.github/actions/init-workspace
      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace
      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{ github.event.pull_request.number }}
          path: paper-server/build/libs/paper-paperclip-*-mojmap.jar
      - name: Publish Artifacts
        uses: PaperMC/action-pr-publishing/upload@paper
        with:
          publishing-task: ":paper-api:publishAllPublicationsTo_githubPackages_PRsRepository publishDevBundlePublicationTo_githubPackages_PRsRepository -PpublishDevBundle"
      - name: Generate an Application repository access token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: 1408328
          private_key: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}
          repository: ${{ github.repository }}
      - name: Publish PR
        uses: PaperMC/action-pr-publishing@paper
        env:
          GITHUB_TOKEN: ${{ steps.gen_repo_token.outputs.token }}
        with:
          publishing-token: ${{ github.token }}
          uploader-workflow-name: Build Paper Pull Request
          artifacts-base-path: io/papermc/paper
          base-maven-url: 'https://maven-prs.papermc.io'
          self-name: 'papermc-pr-publishing[bot]'