name: Build Paper Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  diffpublish:
    name: Generate Diff Patch
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'publish-diff') }}
    steps:
      - name: git / checkout actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: core / setup
        uses: ./.github/actions/init-workspace
        with:
          directory: .
          hash: ${{ github.event.pull_request.head.sha }}
      - name: core / setup base
        uses: ./.github/actions/init-workspace
        with:
          directory: base
          hash: ${{ github.event.pull_request.base.sha }}
      - name: git / generate diff between repos
        run: |
          diff \
            --unified=3 \
            --recursive \
            --exclude='.git' \
            --exclude='.mcassetsroot' \
            base/paper-server/src/minecraft/java \
            paper-server/src/minecraft/java \
            > raw.diff \
            || true
      - name: git / apply diff to base
        run: |
          git apply \
            --directory=base/paper-server \
            raw.diff
      - name: git / commit diff
        working-directory: 'base/paper-server/src/minecraft/java'
        run: |
          git add .
          git commit -m "Generated Patches Diff"
      - name: git / generate patch
        working-directory: 'base/paper-server/src/minecraft/java'
        run: |
          git format-patch -1 HEAD \
            --stdout \
            --no-signature \
            -- . \
          >${{ github.event.pull_request.number }}-rawdiff.patch
      - name: github / create gist
        uses: ./.github/actions/create-or-edit-gist
        id: gist
        with:
          token: ${{ secrets.GIST_PUBLISH_KEY }}
          file_path: 'base/paper-server/src/minecraft/java/${{ github.event.pull_request.number }}-rawdiff.patch'
      - name: github / find diff comment
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- bot: diff-publish-pr -->'
      - name: github / create or edit diff comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <!-- bot: diff-publish-pr -->
            ## 🖇️ Patch Diff Viewer
            Head over to [diffs.dev](https://diffs.dev), and paste in the URL below to view an enhanced view of the diff:
            ${{ steps.gist.outputs.gist_url }}

            *Last updated for: ${{ github.event.pull_request.head.sha }}*

  paperclip:
    name: Create & Publish Artifacts
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'publish-pr') }}
    permissions:
      packages: write # To upload the PR
      actions: write # To get information about the uploading workflow run and to delete the run artifacts
      contents: write # To download the `maven-publish` artifact, and to be able to create commit comments
      issues: write # To be able to create PR comments
      pull-requests: write # To be able to create PR comments
    steps:
      - name: git / checkout actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: core / setup
        uses: ./.github/actions/init-workspace
        with:
          directory: .
          hash: ${{ github.event.pull_request.head.sha }}
      - name: gradle / create mojang paperclip jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace
      - name: github / upload jar
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{ github.event.pull_request.number }}
          path: paper-server/build/libs/paper-paperclip-*-mojmap.jar
      - name: github / publish publications
        uses: PaperMC/action-pr-publishing/upload@paper
        with:
          publishing-task: ":paper-api:publishAllPublicationsTo_githubPackages_PRsRepository publishDevBundlePublicationTo_githubPackages_PRsRepository -PpublishDevBundle"
      - name: github / generate token
        id: gen_repo_token
        uses: kattecon/gh-app-access-token-gen@v1
        with:
          app_id: 1425941
          private_key: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}
          repository: ${{ github.repository }}
      - name: github / publish artifact
        uses: PaperMC/action-pr-publishing@paper-debugging
        env:
          GITHUB_TOKEN: ${{ steps.gen_repo_token.outputs.token }}
        with:
          publishing-token: ${{ github.token }}
          uploader-workflow-name: Build Paper Pull Request
          artifacts-base-path: io/papermc/paper
          base-maven-url: 'https://maven-prs.papermc.io'
          self-name: 'crazy-owen-test-app[bot]'
