name: Build Paper
on:
  push:

jobs:
  build:
    name: Build Paper
    runs-on: ubuntu-latest
    steps:
      - name: git / checkout actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: core / setup
        uses: ./.github/actions/init-workspace
        with:
          directory: .
          hash: ${{ github.sha }}
      - name: gradle / build
        run: ./gradlew build --stacktrace
      - name: gradle / publish tests
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.sha }}
          event_file: ${{ github.event_path }}
          event_name: ${{ github.event_name }}
          files: "**/build/test-results/test/TEST-*.xml"
          comment_mode: off
